[versions]
kotlinxSerializationJson = "1.11.0"
kotlinxDateTime = "0.8.0"
tgbotapi = "35.1.0"
ktor-bom = "3.5.1"
exposedSqlite = "1.3.1"
postgresql = "42.7.13"
logbackClassic = "1.5.37"

# Plugins
kotlin = "2.4.0"


[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }

# Kotlin Telegram Bot Library
tgbotapi = { module = "dev.inmo:tgbotapi", version.ref = "tgbotapi" }
tgbotapi-core = { module = "dev.inmo:tgbotapi.core", version.ref = "tgbotapi" }
tgbotapi-api = { module = "dev.inmo:tgbotapi.api", version.ref = "tgbotapi" }
tgbotapi-utils = { module = "dev.inmo:tgbotapi.utils", version.ref = "tgbotapi" }

# Ktor Client Library
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor-bom" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp" } # Ktor OkHttp Engine
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging" }

# Exposed SQL library
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposedSqlite" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposedSqlite" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposedSqlite" }

# PostgreSQL Driver Library
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

# Logback Classic Library for SLF4J
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackClassic" }


[bundles]
telegram = ["tgbotapi", "tgbotapi-core", "tgbotapi-api", "tgbotapi-utils"]
ktor = ["ktor-client-core", "ktor-client-okhttp", "ktor-client-content-negotiation", "ktor-server-core", "ktor-server-netty", "ktor-serialization-kotlinx-json", "ktor-client-logging"]
exposed = ["exposed-core", "exposed-dao", "exposed-jdbc"]


[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }